module "atlantis" {
  source                                = "github.com/mattermost/mattermost-cloud-monitoring.git//aws/atlantis?ref=v1.6.0"
  deployment_name                       = var.deployment_name
  atlantis_deployment_name              = var.atlantis_deployment_name
  region                                = var.region
  org_whitelist                         = var.org_whitelist
  gitlab_user                           = var.gitlab_user
  gitlab_token                          = var.gitlab_token
  gitlab_webhook_secret                 = var.gitlab_webhook_secret
  gitlab_hostname                       = var.gitlab_hostname
  atlantis_hostname                     = var.atlantis_hostname
  private_hosted_zoneid                 = var.private_hosted_zoneid
  aws_secretname                        = var.aws_secretname
  nginx_internal_chart_values_directory = var.nginx_internal_chart_values_directory
  atlantis_chart_values_directory       = var.atlantis_chart_values_directory
  atlantis_chart_version                = var.atlantis_chart_version
  terraform_default_version             = var.terraform_default_version
  ami_id                                = var.ami_id
  instance_type                         = var.instance_type
  availability_zone                     = var.availability_zone
  key_name                              = var.key_name
  atlantis_instance_tags                = var.atlantis_instance_tags
  subnet_id                             = var.subnet_id
  security_groups                       = var.security_groups
  vpc_id                                = var.vpc_id
  volume_size                           = var.volume_size
  environment                           = var.environment
  min_size                              = var.min_size
  max_size                              = var.max_size
  desired_capacity                      = var.desired_capacity
}
