{
 "title": "Account View",
 "description": "This is a general view of the account.",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Installations",
   "type": "singlestat",
   "description": "This panel shows the total current active installations in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM\nclusterinstallation\nWHERE\nstate = 'stable'\n"
    }
   ]
  },
  {
   "title": "Failed Installations",
   "type": "singlestat",
   "description": "This panel shows the total failed installations in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM\nclusterinstallation\nWHERE\nstate = 'failed'\n"
    }
   ]
  },
  {
   "title": "Deletion Failed Installations",
   "type": "singlestat",
   "description": "This panel shows the total deletion failed installations in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM\nclusterinstallation\nWHERE\nstate = 'deletion-failed'\n"
    }
   ]
  },
  {
   "title": "Reconciling Installations",
   "type": "singlestat",
   "description": "This panel shows the total failed installations in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM\nclusterinstallation\nWHERE\nstate = 'reconciling'\n"
    }
   ]
  },
  {
   "title": "Reconciling Installations",
   "type": "table",
   "description": "Installations in reconciling state.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\nclusterID, installationid\nFROM\nclusterinstallation\nWHERE\nstate = 'reconciling'\n"
    }
   ]
  },
  {
   "title": "Provisioning VPCs Available",
   "type": "singlestat",
   "description": "This panel shows the current number of available VPCs for the provisioner to pick up.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Limit",
     "metricName": "AvailableVPCs",
     "namespace": "AWS/Grafana",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Occupied Provisioning VPCs",
   "type": "singlestat",
   "description": "This panel shows the total number of Occupied Provisioning VPCs.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expression": "a-b", "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Active Clusters",
   "type": "singlestat",
   "description": "This panel shows the current active clusters in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(id)\nFROM\ncluster\nWHERE\nstate = 'stable'\n"
    }
   ]
  },
  {
   "title": "Failed or Failed-Provisioning Clusters",
   "type": "singlestat",
   "description": "This panel shows the total failed clusters in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(id)\nFROM\ncluster\nWHERE\nstate in ('failed','provisioning-failed')\n"
    }
   ]
  },
  {
   "title": "Deletion Failed Clusters",
   "type": "singlestat",
   "description": "This panel shows the total deletion failed clusters in the account.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(id)\nFROM\ncluster\nWHERE\nstate = 'deletion_failed'\n"
    }
   ]
  },
  {
   "title": "Reconciling Clusters",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(id)\nFROM cluster\nWHERE state = 'creation-requested' OR state = 'provisioning-requested' OR state = 'upgrade-requested'\n"
    }
   ]
  },
  {
   "title": "Load Balancers Available",
   "type": "singlestat",
   "description": "This panel shows the current number of used ELBs in comparison to the current AWS limit.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Remain",
     "expression": "b-a",
     "id": "c",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pods in Fail State",
   "type": "graph",
   "description": "The total number of failed pods in the account.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(kube_pod_status_phase{phase=\"Failed\", clusterID!=\"C&C\"}[5m]))/5"
    }
   ]
  },
  {
   "title": "Pods in CrashLoopBackOff State",
   "type": "graph",
   "description": "The total number of pods in CrashLoopBackOff state in the account.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\", clusterID!=\"C&C\"}[5m]))/5"
    }
   ]
  },
  { "title": "CPU/Memory/Network/Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Avg CPU Usage by Cluster ID",
   "type": "graph",
   "description": "This panel shows the cpu usage per Cluster ID (%)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg((rate(node_cpu_seconds_total{mode=\"idle\", clusterID != \"C&C\"}[5m]))*100) by (clusterID))",
     "legendFormat": "{{ clusterID }}"
    }
   ]
  },
  {
   "title": "Avg Memory Usage by Cluster ID",
   "type": "graph",
   "description": "This panel shows the memory usage per Cluster ID (%)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal_bytes{clusterID != \"C&C\"} - node_memory_MemFree_bytes{clusterID != \"C&C\"} - node_memory_Buffers_bytes{clusterID != \"C&C\"} - node_memory_Cached_bytes{clusterID != \"C&C\"}) / node_memory_MemTotal_bytes{clusterID != \"C&C\"})) by (clusterID) * 100",
     "legendFormat": "{{ clusterID }}"
    }
   ]
  },
  {
   "title": "Network Usage by ClusterID",
   "type": "graph",
   "description": "This panel shows the network usage per Cluster ID (%)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (clusterID) (rate(node_network_receive_bytes_total{device=~\"eth0|eth1\"}[5m])))",
     "legendFormat": "{{ clusterID }}"
    }
   ]
  },
  {
   "title": "Disk Usage by Cluster ID",
   "type": "graph",
   "description": "This panel shows the disk usage per Cluster ID (%)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"/\", clusterID != \"C&C\"} - node_filesystem_free_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"/\", clusterID != \"C&C\"}) / node_filesystem_size_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"/\", clusterID != \"C&C\"}) by (clusterID)* 100",
     "legendFormat": "{{ clusterID }}"
    }
   ]
  },
  {
   "title": "Cluster and Installation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "Stable Cluster and Installation IDs",
   "type": "table",
   "description": "This panel shows the stable Cluster and Installation IDs.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\nclusterID, installationID\nFROM\nclusterinstallation\nWHERE\nstate = 'stable'"
    }
   ]
  },
  {
   "title": "Installations Running More than 7 Days (Oldest First)",
   "type": "table",
   "description": "This table shows all the installations running more than a week.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\nid, dns, to_timestamp(@createat/1000) AT TIME ZONE 'UTC'\nFROM \ninstallation \nWHERE\nstate = 'stable' AND (to_timestamp(@createat/1000) < current_date-interval '7 days')\nORDER BY \n timezone DESC;\n"
    }
   ]
  },
  {
   "title": "Cluster Size and Installation Counts",
   "type": "table",
   "description": "This table shows all the installations running more than a week.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\ncluster.id, cluster.size, cluster.allowInstallations, COUNT(clusterinstallation.id), to_timestamp(@cluster.createat/1000) AT TIME ZONE 'UTC'\nFROM \ncluster\nLEFT JOIN clusterinstallation on clusterinstallation.clusterid = cluster.id\nWHERE \ncluster.state = 'stable' AND (clusterinstallation.deleteat = 0 OR clusterinstallation.deleteat IS NULL)\nGROUP BY cluster.id\nORDER BY \n timezone DESC;\n"
    }
   ]
  }
 ]
}