{
 "title": "Alerting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods in CrashLoopBackOff state",
     "type": "graph",
     "description": "The total number of pods in CrashLoopBackOff state in the account.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\", clusterID!=\"C&C\"}) by (namespace,clusterID))"
      }
     ]
    },
    {
     "title": "Pods in Fail state",
     "type": "graph",
     "description": "The total number of pods in CrashLoopBackOff state in the account.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_pod_status_phase{phase=\"Failed\", clusterID!=\"C&C\"}) by (namespace,clusterID))"
      }
     ]
    },
    {
     "title": "Nodes with Taints",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_node_spec_taint{clusterID!=\"C&C\",key!=\"node-role.kubernetes.io/master\"}) by (clusterID,key,node))"
      }
     ]
    },
    {
     "title": "Nodes with Unready or Unknown Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=~\"false|unknown\",clusterID!=\"C&C\"}) by (clusterID,node,status)"
      }
     ]
    },
    {
     "title": "Avg CPU Usage by Cluster ID",
     "type": "graph",
     "description": "This panel shows the cpu usage per Cluster ID (%)",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg((rate(node_cpu_seconds_total{mode=\"idle\",clusterID!=\"C&C\"}[5m]))*100) by (clusterID))",
       "legendFormat": "{{ clusterID }}"
      }
     ]
    },
    {
     "title": "Avg Memory Usage by Cluster ID",
     "type": "graph",
     "description": "This panel shows the memory usage per Cluster ID (%)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(((node_memory_MemTotal_bytes{clusterID != \"C&C\"} - node_memory_MemFree_bytes{clusterID != \"C&C\"} - node_memory_Buffers_bytes{clusterID != \"C&C\"} - node_memory_Cached_bytes{clusterID != \"C&C\"}) / node_memory_MemTotal_bytes{clusterID != \"C&C\"})) by (clusterID) * 100",
       "legendFormat": "{{ clusterID }}"
      }
     ]
    }
   ]
  },
  { "title": "Installation Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Mattermost CPU Usage vs Limits (2m average)",
   "type": "graph",
   "description": "CPU usage of all the MM pods in the namespace against their resource requests.\n\nCalculation based on https://github.com/google/cadvisor/issues/2026#issuecomment-486134079",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container_name=~\"mm.*\"}[2m])) by (clusterID,namespace) /\nsum(container_spec_cpu_quota{image!=\"\",container_name=~\"mm.*\"}/container_spec_cpu_period{image!=\"\",container_name=~\"mm.*\"}) by (clusterID,namespace) * 100"
    }
   ]
  },
  {
   "title": "Mattermost Memory Usage vs Limits",
   "type": "graph",
   "description": "Memory usage of all the pods in the namespace against their resource requests.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container_name=~\"mm.*\"}) by (clusterID,namespace) / sum(kube_pod_container_resource_limits{resource=\"memory\",container=~\"mm.*\"}) by (clusterID,namespace) * 100"
    }
   ]
  },
  {
   "title": "Mattermost API Requests Per Second (2m average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mattermost_http_requests_total[2m])) by (clusterID,kubernetes_namespace)"
    }
   ]
  },
  {
   "title": "Mattermost Mean API Request Time (5m average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000.0 * sum(rate(mattermost_http_request_duration_seconds_sum[5m])) by (clusterID,kubernetes_namespace) /   sum(rate(mattermost_http_request_duration_seconds_count[5m])) by (clusterID,kubernetes_namespace)"
    }
   ]
  },
  {
   "title": "Mattermost API Errors Per Second (2m average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mattermost_http_errors_total[2m])) by (clusterID,kubernetes_namespace)"
    }
   ]
  }
 ]
}