{
 "title": "Cluster View",
 "description": "This dashboard provides cluster admins with the ability to monitor nodes and identify workload bottlenecks. It can be deployed with PSPs enabled using the following helm chart - https://github.com/pivotal-cf/charts-grafana",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": "SELECT id FROM cluster WHERE deleteat = 0"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "kubernetes_build_info{clusterID=~\"^$cluster$\",kubernetes_io_role=\"master\"}",
     "legendFormat": "{{ gitVersion }}"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\nstate\nFROM \ncluster\nWHERE id = '$cluster'"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{clusterID=~\"^$cluster$\", label_kubernetes_io_role!=\"master\"})"
    }
   ]
  },
  {
   "title": "Total Node AZs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (label_failure_domain_beta_kubernetes_io_zone) (kube_node_labels{clusterID=~\"^$cluster$\",label_kubernetes_io_role!=\"master\"}))"
    }
   ]
  },
  {
   "title": "Total Masters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{clusterID=~\"^$cluster$\", label_kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total Master AZs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (label_failure_domain_beta_kubernetes_io_zone) (kube_node_labels{clusterID=~\"^$cluster$\",label_kubernetes_io_role=\"master\"}))"
    }
   ]
  },
  {
   "title": "Active Installations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM clusterinstallation\nWHERE state = 'stable' AND clusterid = '$cluster'\n"
    }
   ]
  },
  {
   "title": "Failed Installations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM clusterinstallation\nWHERE state = 'failed' AND clusterid = '$cluster'\n"
    }
   ]
  },
  {
   "title": "Reconciling Installations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\nNOW () as time,\ncount(installationid)\nFROM clusterinstallation\nWHERE state = 'reconciling' AND clusterid = '$cluster'\n"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",clusterID=~\"^$cluster$\"}) / sum (machine_memory_bytes{clusterID=~\"^$cluster$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage ($interval avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",clusterID=~\"^$cluster$\"}[$interval])) / sum (machine_cpu_cores{clusterID=~\"^$cluster$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"}) / sum (container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",clusterID=~\"^$cluster$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{clusterID=~\"^$cluster$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",clusterID=~\"^$cluster$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{clusterID=~\"^$cluster$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Pods in Fail State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(kube_pod_status_phase{phase=\"Failed\",clusterID=~\"^$cluster$\",}[5m]))/5"
    }
   ]
  },
  {
   "title": "Pods in CrashLoopBackOff State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\",clusterID=~\"^$cluster$\"}[5m]))/5"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",clusterID=~\"^$cluster$\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Namespace CPU Usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",clusterID=~\"^$cluster$\"}[$interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Network I/O Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{clusterID=~\"^$cluster$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{clusterID=~\"^$cluster$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Namespace Network I/O ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",clusterID=~\"^$cluster$\"}[$interval])) by (namespace)",
     "legendFormat": "-> {{ namespace }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",clusterID=~\"^$cluster$\"}[$interval])) by (namespace)",
     "legendFormat": "<- {{ namespace }}"
    }
   ]
  },
  { "title": "Installation Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Installation Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT\nclusterinstallation.id as \"Cluster Installation ID\", clusterinstallation.installationid as \"Installation ID\", installation.DNS as \"DNS\", clusterinstallation.namespace as \"Namespace\",\ninstallation.ownerid as \"Owner\", clusterinstallation.state as \"State\", installation.version as \"Version\", installation.size as \"Size\",\nto_timestamp(clusterinstallation.createat/1000) AT TIME ZONE 'UTC' as \"Time Created\"\nFROM clusterinstallation\nINNER JOIN installation on clusterinstallation.installationid = installation.id\nWHERE clusterid = '$cluster' and clusterinstallation.deleteat = 0"
    }
   ]
  }
 ]
}