{
 "title": "Installation View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "SELECT id FROM installation WHERE deleteat = 0"
   },
   {
    "name": "namespace",
    "query": "SELECT namespace FROM clusterinstallation WHERE installationid = '$installation'"
   },
   {
    "name": "cluster",
    "query": "SELECT clusterid FROM clusterinstallation WHERE installationid = '$installation'"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT state\nFROM installation\nwhere id = '$installation'"
    }
   ]
  },
  {
   "title": "MM Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT version\nFROM installation\nwhere id = '$installation'"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT DNS\nFROM installation\nwhere id = '$installation'"
    }
   ]
  },
  {
   "title": "Owner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ownerid\nFROM installation\nwhere id = '$installation'"
    }
   ]
  },
  {
   "title": "Affinity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT affinity\nFROM installation\nwhere id = '$installation'"
    }
   ]
  },
  {
   "title": "Mattermost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "Mattermost Memory Usage vs Limits",
   "type": "singlestat",
   "description": "Memory usage of all the pods in the namespace against their resource requests.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=~\"mm.*\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container=~\"mm.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Mattermost CPU Usage vs Limits (2m average)",
   "type": "singlestat",
   "description": "Memory usage of all the pods in the namespace against their resource requests.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=~\"mm.*\"}[2m])) /\nsum(container_spec_cpu_quota{image!=\"\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=~\"mm.*\"}/container_spec_cpu_period{image!=\"\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=~\"mm.*\"}) * 100"
    }
   ]
  },
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "MySQL Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "mysql_version_info{kubernetes_namespace=~\"^$namespace$\"}",
     "legendFormat": "{{ app_kubernetes_io_version }}"
    }
   ]
  },
  {
   "title": "MySQL Memory Usage vs Limits",
   "type": "singlestat",
   "description": "Memory usage of all the MySQL pods in the namespace against their resource requests.",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",pod_name=~\".*mysql.*\"}) / sum(kube_pod_container_resource_limits{resource=\"memory\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\".*mysql.*\"}) * 100"
    }
   ]
  },
  {
   "title": "MySQL Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (pod) (kube_pod_container_info{namespace=~\"^$namespace$\",clusterID=~\"^$cluster$\",container=\"mysql\"}))"
    }
   ]
  },
  {
   "title": "MySQL CPU Usage vs Limits (2m average)",
   "type": "singlestat",
   "description": "Memory usage of all the MySQL pods in the namespace against their resource requests.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=\"mysql\"}[2m])) / sum(kube_pod_container_resource_limits{resource=\"cpu\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",pod=~\".*mysql.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Database Type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT database\nFROM installation\nwhere id = '$installation'"
    }
   ]
  },
  {
   "title": "MySQL Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=\"mysql\"})"
    }
   ]
  },
  {
   "title": "MySQL CPU Usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",clusterID=~\"^$cluster$\",namespace=~\"^$namespace$\",container_name=\"mysql\"}[2m]))"
    }
   ]
  },
  {
   "title": "MinIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  }
 ]
}