{
 "title": "Uptime View",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "targets", "label": "targets", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime per Service",
   "type": "bargauge",
   "description": "This diagram shows the total uptime per service in the last 24 hours.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum_over_time(probe_http_status_code{instance=~\"$targets\"}[$__range])/(200))/$__range_s*100*60",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Non-200 HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"} != 200",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Prob Duration ($targets)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~'$targets'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "General Status ",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum_over_time(probe_success{instance=~\"$targets\"}[1m])"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$targets\"}-time()"
    },
    {}
   ]
  }
 ]
}