kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
  nodeSelector:
    calico: "true"
  tolerations:
    - key: "calico"
      operator: "Exists"
      effect: "NoSchedule"
