apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: pgbouncer
    name: pgbouncer
  name: pgbouncer
---
apiVersion: v1
data:
  pgbouncer.ini: |2

    [pgbouncer]
    listen_addr = *
    listen_port = 5432
    auth_type = any
    admin_users = admin
    ignore_startup_parameters = extra_float_digits
    tcp_keepalive = 1
    tcp_keepcnt = 5
    tcp_keepidle = 5
    tcp_keepintvl = 1
    server_round_robin = 1
    log_disconnections = 1
    log_connections = 1
    pool_mode = transaction
    min_pool_size = 1
    default_pool_size = 5
    reserve_pool_size = 10
    reserve_pool_timeout = 1
    max_client_conn = 20000
    max_db_connections = 20
    server_idle_timeout = 30
    server_lifetime = 300
    server_reset_query_always = 0

    [databases]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: pgbouncer
    app.kubernetes.io/managed-by: provisioner
    app.kubernetes.io/name: pgbouncer
  name: pgbouncer-configmap
  namespace: pgbouncer
---
apiVersion: v1
data:
  userlist.txt: Zm9vCg== # foo
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: pgbouncer
    app.kubernetes.io/managed-by: provisioner
    app.kubernetes.io/name: pgbouncer
  name: pgbouncer-userlist-secret
  namespace: pgbouncer
type: Opaque
