// Code generated by MockGen. DO NOT EDIT.
// Source: aws.go

// Package mock_main is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ec2 "github.com/aws/aws-sdk-go/service/ec2"
	gomock "github.com/golang/mock/gomock"
)

// MockResourcer is a mock of Resourcer interface.
type MockResourcer struct {
	ctrl     *gomock.Controller
	recorder *MockResourcerMockRecorder
}

// MockResourcerMockRecorder is the mock recorder for MockResourcer.
type MockResourcerMockRecorder struct {
	mock *MockResourcer
}

// NewMockResourcer creates a new mock instance.
func NewMockResourcer(ctrl *gomock.Controller) *MockResourcer {
	mock := &MockResourcer{ctrl: ctrl}
	mock.recorder = &MockResourcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcer) EXPECT() *MockResourcerMockRecorder {
	return m.recorder
}

// DeleteVolume mocks base method.
func (m *MockResourcer) DeleteVolume(context context.Context, volumeID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVolume", context, volumeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVolume indicates an expected call of DeleteVolume.
func (mr *MockResourcerMockRecorder) DeleteVolume(context, volumeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVolume", reflect.TypeOf((*MockResourcer)(nil).DeleteVolume), context, volumeID)
}

// ListVolumes mocks base method.
func (m *MockResourcer) ListVolumes(context context.Context, volumeState string) ([]*ec2.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", context, volumeState)
	ret0, _ := ret[0].([]*ec2.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockResourcerMockRecorder) ListVolumes(context, volumeState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockResourcer)(nil).ListVolumes), context, volumeState)
}
