apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-node
  name: felix-metrics-svc
  namespace: calico-system
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: calico-node
  sessionAffinity: None
  type: ClusterIP
