replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
image:
  repository: chartmuseum/chartmuseum
  tag: v0.12.0
  pullPolicy: IfNotPresent
env:
  open:
    DISABLE_API: false
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: 
    STORAGE_AMAZON_PREFIX:
    STORAGE_AMAZON_REGION: us-east-1
  secret:
    AWS_ACCESS_KEY_ID: "" ## aws access key id value
    AWS_SECRET_ACCESS_KEY: "" ## aws access key secret value

## Ingress for load balancer
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    kubernetes.io/ingress.provider: nginx
  hosts:
    - name: 
      path: /
      tls: true 
