[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.13.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.25.4"

[[constraint]]
  name = "github.com/kubernetes-sigs/aws-iam-authenticator"
  version = "0.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[prune]
  go-tests = true
  unused-packages = true
