// Code generated by MockGen. DO NOT EDIT.
// Source: aws.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResourcer is a mock of Resourcer interface.
type MockResourcer struct {
	ctrl     *gomock.Controller
	recorder *MockResourcerMockRecorder
}

// MockResourcerMockRecorder is the mock recorder for MockResourcer.
type MockResourcerMockRecorder struct {
	mock *MockResourcer
}

// NewMockResourcer creates a new mock instance.
func NewMockResourcer(ctrl *gomock.Controller) *MockResourcer {
	mock := &MockResourcer{ctrl: ctrl}
	mock.recorder = &MockResourcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcer) EXPECT() *MockResourcerMockRecorder {
	return m.recorder
}

// DeleteCalssiclbs mocks base method.
func (m *MockResourcer) DeleteCalssiclbs(context context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCalssiclbs", context)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCalssiclbs indicates an expected call of DeleteCalssiclbs.
func (mr *MockResourcerMockRecorder) DeleteCalssiclbs(context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCalssiclbs", reflect.TypeOf((*MockResourcer)(nil).DeleteCalssiclbs), context)
}

// DeleteElbs mocks base method.
func (m *MockResourcer) DeleteElbs(context context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteElbs", context)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteElbs indicates an expected call of DeleteElbs.
func (mr *MockResourcerMockRecorder) DeleteElbs(context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteElbs", reflect.TypeOf((*MockResourcer)(nil).DeleteElbs), context)
}
